steps:
name: Azure Subscription Scanner
on: [push]
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: SubscriptionSecScan.exe
      uses: saikishoretayi/Azsubscanner@v1

    - name: SubscriptionSecScan Push
      run: SubscriptionSecScan push *.exe
